# Generated by Django 5.1.7 on 2025-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_entry',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of views', verbose_name='visits counter'),
        ),
    ]
