# Generated by Django 5.1.7 on 2025-03-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, verbose_name='название категории')),
                ('description', models.TextField(blank=True, help_text='describe the category', null=True, verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product's name", max_length=100, verbose_name='название продукта')),
                ('description', models.TextField(blank=True, help_text='describe the product', null=True, verbose_name='описание продукта')),
                ('preview', models.ImageField(blank=True, help_text='Upload photo', null=True, upload_to='products/media', verbose_name='превью продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(blank=True, help_text='date when added', null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, help_text='date when changed', null=True, verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(help_text='select product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='категория продукта')),
            ],
        ),
    ]
