# Generated by Django 5.1.7 on 2025-04-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, help_text='Upload photo', null=True, upload_to='products/photo', verbose_name='превью продукта'),
        ),
    ]
