# Generated by Django 4.2.2 on 2025-05-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_change_category', 'can change category'), ('can_edit_description', 'can edit description'), ('can_edit_publication', 'can change publication'), ('can_unpublish_product', 'can unpublish product'), ('can_delete_product', 'can delete product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
